<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="IgnaciaCS">

<title>Trabajo02</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Trabajo02_files/libs/clipboard/clipboard.min.js"></script>
<script src="Trabajo02_files/libs/quarto-html/quarto.js"></script>
<script src="Trabajo02_files/libs/quarto-html/popper.min.js"></script>
<script src="Trabajo02_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Trabajo02_files/libs/quarto-html/anchor.min.js"></script>
<link href="Trabajo02_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Trabajo02_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Trabajo02_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Trabajo02_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Trabajo02_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#trabajo-02-r-para-análisis-estadístico" id="toc-trabajo-02-r-para-análisis-estadístico" class="nav-link active" data-scroll-target="#trabajo-02-r-para-análisis-estadístico">Trabajo 02: R para Análisis Estadístico</a>
  <ul class="collapse">
  <li><a href="#por-ignacia-castillo-soto" id="toc-por-ignacia-castillo-soto" class="nav-link" data-scroll-target="#por-ignacia-castillo-soto">Por: Ignacia Castillo Soto</a>
  <ul class="collapse">
  <li><a href="#mercantilización-del-sistema-educativo-y-segregación-escolar-en-chile" id="toc-mercantilización-del-sistema-educativo-y-segregación-escolar-en-chile" class="nav-link" data-scroll-target="#mercantilización-del-sistema-educativo-y-segregación-escolar-en-chile">Mercantilización del sistema educativo y segregación escolar en Chile</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajo02</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>IgnaciaCS </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="trabajo-02-r-para-análisis-estadístico" class="level1">
<h1>Trabajo 02: R para Análisis Estadístico</h1>
<section id="por-ignacia-castillo-soto" class="level2">
<h2 class="anchored" data-anchor-id="por-ignacia-castillo-soto">Por: Ignacia Castillo Soto</h2>
<section id="mercantilización-del-sistema-educativo-y-segregación-escolar-en-chile" class="level3">
<h3 class="anchored" data-anchor-id="mercantilización-del-sistema-educativo-y-segregación-escolar-en-chile">Mercantilización del sistema educativo y segregación escolar en Chile</h3>
<section id="introducción1" class="level4">
<h4 class="anchored" data-anchor-id="introducción1">Introducción<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></h4>
<p>Para esta segunda entrega decidí utilizar la base de datos del SIMCE 2017<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> para los cursos de 2° medio a nivel país, ya que me parece que trabajar con adolescentes que están en su última etapa de formación académica es un buen grupo para analizar las variables y porque han estado la mayoría de su vida escolar expuestos al sistema educativo y se puede ver como afecta a los resultados dentro de distintos establecimientos.</p>
<p>Dentro de los antecedentes de la bb.dd. Simce es parte de las evaluaciones que se aplican en Chile, definidas en el Plan de Evaluaciones Nacionales e Internacionales, y corresponde a una medición estandarizada anual a todas y todos los estudiantes del país que cursan los niveles evaluados. Su objetivo es conocer los resultados educativos de los establecimientos, evaluando el logro de los contenidos y habilidades del Currículum Nacional, con pruebas en diferentes asignaturas o áreas de aprendizaje; y recogiendo información sobre el contexto educativo a través de cuestionarios que responden directores(as), docentes, estudiantes, padres, madres y apoderados, de modo de analizar los resultados en forma integral. <a href="https://www.agenciaeducacion.cl/simce/" class="uri">https://www.agenciaeducacion.cl/simce/</a></p>
<p>Las variables que seleccioné para este trabajo son de tipo categóricas, y pertenecen a los establecimientos evaluados el año 2017</p>
<ul>
<li><p>VARIABLE 1:“cod_depe2” = Código de dependencia 3 categorías (Municipal(1); Particular subvencionado(2); Particular pagado(3))</p></li>
<li><p>VARIABLE 2: “cod_grupo” = Código de grupo socioeconómico (Bajo(1);Medio bajo(2);Medio(3);Medio alto(4);Alto(5))</p></li>
<li><p>VARIABLE 3: “cdm_2017” = Categoría de Desempeño 2017 (INSUFICIENTE, MEDIO-BAJO, MEDIO Y ALTO)<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<ul>
<li><p>Los establecimientos que tengan valores del Índice Final hasta el valor del percentil 12 (inclusive) de la distribución de este índice se clasificarán en la categoría Desempeño Insuficiente.</p></li>
<li><p>Los establecimientos que presenten valores del Índice Final por sobre el valor del percentil 12 y hasta el percentil 35 (inclusive) se clasificarán en la categoría Desempeño Medio-Bajo.</p></li>
<li><p>Los establecimientos que se sitúen por sobre el valor del percentil 35 y hasta el percentil 85 (inclusive) de la distribución del índice Final se clasificarán en la categoría Desempeño Medio.</p></li>
<li><p>Los establecimientos con valores del Índice Final superiores al valor del percentil 85 de la distribución de este índice se clasificarán en la categoría Desempeño Alto.</p></li>
</ul></li>
</ul>
</section>
<section id="cargar-base-de-datos" class="level4">
<h4 class="anchored" data-anchor-id="cargar-base-de-datos">1. Cargar base de datos</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Librerías a utilizar</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(dplyr, </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>               sjmisc, </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>               car, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>               sjlabelled, </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>               stargazer, </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>               haven,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>               kableExtra,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>               sjPlot,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>               summarytools,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>               ggplot2)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Carga de la base de datos</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())       </span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">999</span>) </span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>cdm_2017 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"C:/Users/nachi/OneDrive/Documentos/Universidad/UAH 5° Semestre/OFC R para análisis estadístico/Trabajos/input/data-orig/cdm_2017.xlsx"</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>idps2m2017_rbd <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"C:/Users/nachi/OneDrive/Documentos/Universidad/UAH 5° Semestre/OFC R para análisis estadístico/Trabajos/input/data-orig/idps2m2017_rbd.xlsx"</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>simce2m2017_rbd <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"C:/Users/nachi/OneDrive/Documentos/Universidad/UAH 5° Semestre/OFC R para análisis estadístico/Trabajos/input/data-orig/simce2m2017_rbd.xlsx"</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(cdm_2017)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2914    7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(idps2m2017_rbd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2912   18</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(simce2m2017_rbd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2923   49</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(cdm_2017)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(idps2m2017_rbd)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(simce2m2017_rbd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="selección-de-variables" class="level4">
<h4 class="anchored" data-anchor-id="selección-de-variables">2. Selección de variables</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Selección de Variables a utilizar</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co">#De la base "cdm_2017"</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># "rbd" = Rol base de datos del establecimiento</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># "cdm_2017" = Categoría de Desempeño 2017 (INSUFICIENTE, MEDIO-BAJO, MEDIO Y ALTO)</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">find_var</span>(<span class="at">data =</span> cdm_2017, <span class="st">"rbd"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  col.nr    var.name   var.label
1      1         rbd         rbd
2      2     nom_rbd     nom_rbd
3      3 nom_reg_rbd nom_reg_rbd
4      4 nom_com_rbd nom_com_rbd</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">find_var</span>(<span class="at">data =</span> cdm_2017, <span class="st">"cdm_2017"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  col.nr var.name var.label
1      7 cdm_2017  cdm_2017</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>proc_cdm_2017 <span class="ot">&lt;-</span> cdm_2017 <span class="sc">%&gt;%</span> <span class="fu">select</span>(rbd,cdm_2017)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(proc_cdm_2017)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "rbd"      "cdm_2017"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>sjlabelled<span class="sc">::</span><span class="fu">get_label</span>(proc_cdm_2017)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     rbd cdm_2017 
      ""       "" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(proc_cdm_2017)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2914    2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(cdm_2017)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(proc_cdm_2017,<span class="at">file =</span> <span class="st">"C:/Users/nachi/OneDrive/Documentos/Universidad/UAH 5° Semestre/OFC R para análisis estadístico/Trabajos/input/data-proc/proc_cdm_2017.RData"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co">#De la base "idps2m2017_rbd"</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co"># "rbd" = Rol base de datos del establecimiento</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co"># "cod_depe2" = Código de dependencia 3 categorías (Municipal(1); Particular subvencionado(2); Particular pagado(3))</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="fu">find_var</span>(<span class="at">data =</span> idps2m2017_rbd, <span class="st">"rbd"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   col.nr       var.name      var.label
1       3            rbd            rbd
2       4        nom_rbd        nom_rbd
3       5    cod_reg_rbd    cod_reg_rbd
4       6    nom_reg_rbd    nom_reg_rbd
5       7    cod_pro_rbd    cod_pro_rbd
6       8    nom_pro_rbd    nom_pro_rbd
7       9    cod_com_rbd    cod_com_rbd
8      10    nom_com_rbd    nom_com_rbd
9      11 nom_deprov_rbd nom_deprov_rbd
10     14  cod_rural_rbd  cod_rural_rbd</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">find_var</span>(<span class="at">data =</span> idps2m2017_rbd, <span class="st">"cod_depe2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  col.nr  var.name var.label
1     12 cod_depe2 cod_depe2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>proc_idps2m2017_rbd <span class="ot">&lt;-</span> idps2m2017_rbd <span class="sc">%&gt;%</span> <span class="fu">select</span>(rbd,cod_depe2)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(proc_idps2m2017_rbd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "rbd"       "cod_depe2"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>sjlabelled<span class="sc">::</span><span class="fu">get_label</span>(proc_idps2m2017_rbd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      rbd cod_depe2 
       ""        "" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(proc_idps2m2017_rbd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2912    2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(proc_idps2m2017_rbd)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(proc_idps2m2017_rbd,<span class="at">file =</span> <span class="st">"C:/Users/nachi/OneDrive/Documentos/Universidad/UAH 5° Semestre/OFC R para análisis estadístico/Trabajos/input/data-proc/proc_idps2m2017_rbd.RData"</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co">#De la base "simce2m2017_rbd"</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="co"># "rbd" = Rol base de datos del establecimiento</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co"># "cod_grupo" = Código de grupo socioeconómico (Bajo(1);Medio bajo(2);Medio(3);Medio alto(4);Alto(5))</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="fu">find_var</span>(<span class="at">data =</span> simce2m2017_rbd, <span class="st">"rbd"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   col.nr                var.name               var.label
1       5                     rbd                     rbd
2       6                   dvrbd                   dvrbd
3       7                 nom_rbd                 nom_rbd
4       8             cod_reg_rbd             cod_reg_rbd
5       9             nom_reg_rbd             nom_reg_rbd
6      10             cod_pro_rbd             cod_pro_rbd
7      11             nom_pro_rbd             nom_pro_rbd
8      12             cod_com_rbd             cod_com_rbd
9      13             nom_com_rbd             nom_com_rbd
10     14          nom_deprov_rbd          nom_deprov_rbd
11     18           cod_rural_rbd           cod_rural_rbd
12     19         nalu_lect2m_rbd         nalu_lect2m_rbd
13     20         nalu_mate2m_rbd         nalu_mate2m_rbd
14     21          nalu_soc2m_rbd          nalu_soc2m_rbd
15     22         prom_lect2m_rbd         prom_lect2m_rbd
16     23         prom_mate2m_rbd         prom_mate2m_rbd
17     24          prom_soc2m_rbd          prom_soc2m_rbd
18     25          dif_lect2m_rbd          dif_lect2m_rbd
19     26          dif_mate2m_rbd          dif_mate2m_rbd
20     27           dif_soc2m_rbd           dif_soc2m_rbd
21     28       difgru_lect2m_rbd       difgru_lect2m_rbd
22     29       difgru_mate2m_rbd       difgru_mate2m_rbd
23     30        difgru_soc2m_rbd        difgru_soc2m_rbd
24     31       sigdif_lect2m_rbd       sigdif_lect2m_rbd
25     32       sigdif_mate2m_rbd       sigdif_mate2m_rbd
26     33        sigdif_soc2m_rbd        sigdif_soc2m_rbd
27     34       siggru_lect2m_rbd       siggru_lect2m_rbd
28     35       siggru_mate2m_rbd       siggru_mate2m_rbd
29     36        siggru_soc2m_rbd        siggru_soc2m_rbd
30     37        marca_lect2m_rbd        marca_lect2m_rbd
31     38        marca_mate2m_rbd        marca_mate2m_rbd
32     39         marca_soc2m_rbd         marca_soc2m_rbd
33     40     marcadif_lect2m_rbd     marcadif_lect2m_rbd
34     41     marcadif_mate2m_rbd     marcadif_mate2m_rbd
35     42      marcadif_soc2m_rbd      marcadif_soc2m_rbd
36     43 palu_eda_ins_lect2m_rbd palu_eda_ins_lect2m_rbd
37     44 palu_eda_ele_lect2m_rbd palu_eda_ele_lect2m_rbd
38     45 palu_eda_ade_lect2m_rbd palu_eda_ade_lect2m_rbd
39     46 palu_eda_ins_mate2m_rbd palu_eda_ins_mate2m_rbd
40     47 palu_eda_ele_mate2m_rbd palu_eda_ele_mate2m_rbd
41     48 palu_eda_ade_mate2m_rbd palu_eda_ade_mate2m_rbd</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">find_var</span>(<span class="at">data =</span> simce2m2017_rbd, <span class="st">"cod_grupo"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  col.nr  var.name var.label
1     17 cod_grupo cod_grupo</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>proc_simce2m2017_rbd <span class="ot">&lt;-</span> simce2m2017_rbd <span class="sc">%&gt;%</span> <span class="fu">select</span>(rbd,cod_grupo)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(proc_simce2m2017_rbd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "rbd"       "cod_grupo"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>sjlabelled<span class="sc">::</span><span class="fu">get_label</span>(proc_simce2m2017_rbd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      rbd cod_grupo 
       ""        "" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(proc_simce2m2017_rbd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2923    2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(proc_simce2m2017_rbd)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(proc_simce2m2017_rbd,<span class="at">file =</span> <span class="st">"C:/Users/nachi/OneDrive/Documentos/Universidad/UAH 5° Semestre/OFC R para análisis estadístico/Trabajos/input/data-proc/proc_simce2m2017_rbd.RData"</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Nueva base procesada</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Unir por "rbd"</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">merge</span>(proc_cdm_2017,proc_idps2m2017_rbd, <span class="at">by=</span><span class="st">"rbd"</span>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>simce2m2017_total <span class="ot">&lt;-</span> <span class="fu">merge</span> (data, proc_simce2m2017_rbd, <span class="at">by=</span><span class="st">"rbd"</span>)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(simce2m2017_total)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "rbd"       "cdm_2017"  "cod_depe2" "cod_grupo"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>sjlabelled<span class="sc">::</span><span class="fu">get_label</span>(simce2m2017_total)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      rbd  cdm_2017 cod_depe2 cod_grupo 
       ""        ""        ""        "" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">find_var</span>(<span class="at">data =</span> simce2m2017_total, <span class="st">"cdm_2017"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  col.nr var.name var.label
1      2 cdm_2017  cdm_2017</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">find_var</span>(<span class="at">data =</span> simce2m2017_total, <span class="st">"cod_depe2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  col.nr  var.name var.label
1      3 cod_depe2 cod_depe2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">find_var</span>(<span class="at">data =</span> simce2m2017_total,<span class="st">"cod_grupo"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  col.nr  var.name var.label
1      4 cod_grupo cod_grupo</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>simce2m2017_total <span class="ot">&lt;-</span> simce2m2017_total <span class="sc">%&gt;%</span> <span class="fu">select</span>(cdm_2017,cod_depe2,cod_grupo)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(simce2m2017_total)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2876    3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(simce2m2017_total)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(simce2m2017_total,<span class="at">file =</span> <span class="st">"C:/Users/nachi/OneDrive/Documentos/Universidad/UAH 5° Semestre/OFC R para análisis estadístico/Trabajos/input/data-proc/simce2m2017_total.RData"</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"~/Universidad/UAH 5° Semestre/OFC R para análisis estadístico/Trabajos/input/data-proc/simce2m2017_total.RData"</span>)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(simce2m2017_total)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="operacionalización-de-variables" class="level4">
<h4 class="anchored" data-anchor-id="operacionalización-de-variables">3. Operacionalización de variables</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Procesamiento de Variables</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="co">#VARIABLE 1:"cod_depe2" = Código de dependencia 3 categorías (Municipal(1); Particular subvencionado(2); Particular pagado(3))</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="co">#a. Descriptivo</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(simce2m2017_total<span class="sc">$</span>cod_depe2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;character&gt; 
# total N=2876 valid N=2876 mean=2.30 sd=0.88

Value                    |    N | Raw % | Valid % | Cum. %
----------------------------------------------------------
Municipal                |  805 | 27.99 |   27.99 |  27.99
Particular pagado        |  395 | 13.73 |   13.73 |  41.72
Particular subvencionado | 1676 | 58.28 |   58.28 | 100.00
&lt;NA&gt;                     |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(simce2m2017_total<span class="sc">$</span>cod_depe2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
               Municipal        Particular pagado Particular subvencionado 
                     805                      395                     1676 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#b. Recodificar/ reordenar</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>simce2m2017_total<span class="sc">$</span>cod_depe2 <span class="ot">=</span> <span class="fu">factor</span>(simce2m2017_total<span class="sc">$</span>cod_depe2, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Municipal"</span>, <span class="st">"Particular subvencionado"</span>,<span class="st">"Particular pagado"</span>))</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(simce2m2017_total<span class="sc">$</span>cod_depe2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;categorical&gt; 
# total N=2876 valid N=2876 mean=1.86 sd=0.63

Value                    |    N | Raw % | Valid % | Cum. %
----------------------------------------------------------
Municipal                |  805 | 27.99 |   27.99 |  27.99
Particular subvencionado | 1676 | 58.28 |   58.28 |  86.27
Particular pagado        |  395 | 13.73 |   13.73 | 100.00
&lt;NA&gt;                     |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(simce2m2017_total<span class="sc">$</span>cod_depe2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
               Municipal Particular subvencionado        Particular pagado 
                     805                     1676                      395 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co">#c. Etiquetado</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(simce2m2017_total<span class="sc">$</span>cod_depe2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>simce2m2017_total<span class="sc">$</span>cod_depe2 <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> simce2m2017_total<span class="sc">$</span>cod_depe2,<span class="at">label =</span> <span class="st">"Código dependencia"</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="co">#VARIABLE 2: "cod_grupo" = Código de grupo socioeconómico (Bajo(1);Medio bajo(2);Medio(3);Medio alto(4);Alto(5))</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="co">#a. Descriptivo</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(simce2m2017_total<span class="sc">$</span>cod_grupo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;character&gt; 
# total N=2876 valid N=2876 mean=3.21 sd=1.41

Value      |   N | Raw % | Valid % | Cum. %
-------------------------------------------
Alto       | 390 | 13.56 |   13.56 |  13.56
Bajo       | 628 | 21.84 |   21.84 |  35.40
Medio      | 674 | 23.44 |   23.44 |  58.83
Medio alto | 368 | 12.80 |   12.80 |  71.63
Medio bajo | 816 | 28.37 |   28.37 | 100.00
&lt;NA&gt;       |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(simce2m2017_total<span class="sc">$</span>cod_grupo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      Alto       Bajo      Medio Medio alto Medio bajo 
       390        628        674        368        816 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co">#b. Recodificar/ reordenar</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>simce2m2017_total<span class="sc">$</span>cod_grupo <span class="ot">=</span> <span class="fu">factor</span>(simce2m2017_total<span class="sc">$</span>cod_grupo, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Bajo"</span>,<span class="st">"Medio bajo"</span>,<span class="st">"Medio"</span>,<span class="st">"Medio alto"</span>,<span class="st">"Alto"</span>))</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(simce2m2017_total<span class="sc">$</span>cod_grupo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;categorical&gt; 
# total N=2876 valid N=2876 mean=2.68 sd=1.31

Value      |   N | Raw % | Valid % | Cum. %
-------------------------------------------
Bajo       | 628 | 21.84 |   21.84 |  21.84
Medio bajo | 816 | 28.37 |   28.37 |  50.21
Medio      | 674 | 23.44 |   23.44 |  73.64
Medio alto | 368 | 12.80 |   12.80 |  86.44
Alto       | 390 | 13.56 |   13.56 | 100.00
&lt;NA&gt;       |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(simce2m2017_total<span class="sc">$</span>cod_grupo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      Bajo Medio bajo      Medio Medio alto       Alto 
       628        816        674        368        390 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co">#c. Etiquetado</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>simce2m2017_total<span class="sc">$</span>cod_grupo<span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> simce2m2017_total<span class="sc">$</span>cod_grupo,<span class="at">label =</span> <span class="st">"GSE"</span>)</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a><span class="co">#VARIABLE 3: "cdm_2017" = Categoría de Desempeño 2017 (INSUFICIENTE, MEDIO-BAJO, MEDIO Y ALTO)</span></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(simce2m2017_total<span class="sc">$</span>cdm_2017)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;character&gt; 
# total N=2876 valid N=2876 mean=2.89 sd=1.04

Value         |    N | Raw % | Valid % | Cum. %
-----------------------------------------------
ALTO          |  429 | 14.92 |   14.92 |  14.92
INSUFICIENTE  |  332 | 11.54 |   11.54 |  26.46
MEDIO         | 1340 | 46.59 |   46.59 |  73.05
MEDIO-BAJO    |  664 | 23.09 |   23.09 |  96.14
SIN CATEGORIA |  111 |  3.86 |    3.86 | 100.00
&lt;NA&gt;          |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(simce2m2017_total<span class="sc">$</span>cdm_2017)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
         ALTO  INSUFICIENTE         MEDIO    MEDIO-BAJO SIN CATEGORIA 
          429           332          1340           664           111 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co">#b. Recodificar/ reordenar</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>simce2m2017_total<span class="sc">$</span>cdm_2017 <span class="ot">=</span> <span class="fu">factor</span>(simce2m2017_total<span class="sc">$</span>cdm_2017, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"SIN CATEGORIA"</span>,<span class="st">"INSUFICIENTE"</span>,<span class="st">"MEDIO-BAJO"</span>,<span class="st">"MEDIO"</span>,<span class="st">"ALTO"</span>))</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(simce2m2017_total<span class="sc">$</span>cdm_2017)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;categorical&gt; 
# total N=2876 valid N=2876 mean=3.57 sd=1.00

Value         |    N | Raw % | Valid % | Cum. %
-----------------------------------------------
SIN CATEGORIA |  111 |  3.86 |    3.86 |   3.86
INSUFICIENTE  |  332 | 11.54 |   11.54 |  15.40
MEDIO-BAJO    |  664 | 23.09 |   23.09 |  38.49
MEDIO         | 1340 | 46.59 |   46.59 |  85.08
ALTO          |  429 | 14.92 |   14.92 | 100.00
&lt;NA&gt;          |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(simce2m2017_total<span class="sc">$</span>cdm_2017)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
SIN CATEGORIA  INSUFICIENTE    MEDIO-BAJO         MEDIO          ALTO 
          111           332           664          1340           429 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Casos perdidos</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>simce2m2017_total <span class="ot">&lt;-</span> simce2m2017_total <span class="sc">%&gt;%</span> </span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(., <span class="at">cdm_2017 =</span> (<span class="fu">case_when</span>(cdm_2017 <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"SIN CATEGORIA"</span>)<span class="sc">~</span><span class="cn">NA_character_</span>,</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="cn">TRUE</span><span class="sc">~</span>cdm_2017)))</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(simce2m2017_total<span class="sc">$</span>cdm_2017)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;character&gt; 
# total N=2876 valid N=2765 mean=2.81 sd=0.97

Value        |    N | Raw % | Valid % | Cum. %
----------------------------------------------
ALTO         |  429 | 14.92 |   15.52 |  15.52
INSUFICIENTE |  332 | 11.54 |   12.01 |  27.52
MEDIO        | 1340 | 46.59 |   48.46 |  75.99
MEDIO-BAJO   |  664 | 23.09 |   24.01 | 100.00
&lt;NA&gt;         |  111 |  3.86 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(simce2m2017_total<span class="sc">$</span>cdm_2017)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        ALTO INSUFICIENTE        MEDIO   MEDIO-BAJO 
         429          332         1340          664 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>simce2m2017_total<span class="sc">$</span>cdm_2017 <span class="ot">=</span> <span class="fu">factor</span>(simce2m2017_total<span class="sc">$</span>cdm_2017, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"INSUFICIENTE"</span>,<span class="st">"MEDIO-BAJO"</span>,<span class="st">"MEDIO"</span>,<span class="st">"ALTO"</span>))</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(simce2m2017_total<span class="sc">$</span>cdm_2017)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;categorical&gt; 
# total N=2876 valid N=2765 mean=2.67 sd=0.88

Value        |    N | Raw % | Valid % | Cum. %
----------------------------------------------
INSUFICIENTE |  332 | 11.54 |   12.01 |  12.01
MEDIO-BAJO   |  664 | 23.09 |   24.01 |  36.02
MEDIO        | 1340 | 46.59 |   48.46 |  84.48
ALTO         |  429 | 14.92 |   15.52 | 100.00
&lt;NA&gt;         |  111 |  3.86 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(simce2m2017_total<span class="sc">$</span>cdm_2017)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
INSUFICIENTE   MEDIO-BAJO        MEDIO         ALTO 
         332          664         1340          429 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co">#c. Etiquetado</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>simce2m2017_total<span class="sc">$</span>cdm_2017<span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> simce2m2017_total<span class="sc">$</span>cdm_2017,<span class="at">label =</span> <span class="st">"Categoría desempeño"</span>)</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Verificar descriptivos</span></span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(simce2m2017_total<span class="sc">$</span>cod_depe2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Código dependencia (x) &lt;categorical&gt; 
# total N=2876 valid N=2876 mean=1.86 sd=0.63

Value                    |    N | Raw % | Valid % | Cum. %
----------------------------------------------------------
Municipal                |  805 | 27.99 |   27.99 |  27.99
Particular subvencionado | 1676 | 58.28 |   58.28 |  86.27
Particular pagado        |  395 | 13.73 |   13.73 | 100.00
&lt;NA&gt;                     |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(simce2m2017_total<span class="sc">$</span>cod_grupo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>GSE (x) &lt;categorical&gt; 
# total N=2876 valid N=2876 mean=2.68 sd=1.31

Value      |   N | Raw % | Valid % | Cum. %
-------------------------------------------
Bajo       | 628 | 21.84 |   21.84 |  21.84
Medio bajo | 816 | 28.37 |   28.37 |  50.21
Medio      | 674 | 23.44 |   23.44 |  73.64
Medio alto | 368 | 12.80 |   12.80 |  86.44
Alto       | 390 | 13.56 |   13.56 | 100.00
&lt;NA&gt;       |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(simce2m2017_total<span class="sc">$</span>cdm_2017)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Categoría desempeño (x) &lt;categorical&gt; 
# total N=2876 valid N=2765 mean=2.67 sd=0.88

Value        |    N | Raw % | Valid % | Cum. %
----------------------------------------------
INSUFICIENTE |  332 | 11.54 |   12.01 |  12.01
MEDIO-BAJO   |  664 | 23.09 |   24.01 |  36.02
MEDIO        | 1340 | 46.59 |   48.46 |  84.48
ALTO         |  429 | 14.92 |   15.52 | 100.00
&lt;NA&gt;         |  111 |  3.86 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(simce2m2017_total<span class="sc">$</span>cod_depe2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
               Municipal Particular subvencionado        Particular pagado 
                     805                     1676                      395 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(simce2m2017_total<span class="sc">$</span>cod_grupo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      Bajo Medio bajo      Medio Medio alto       Alto 
       628        816        674        368        390 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(simce2m2017_total<span class="sc">$</span>cdm_2017)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
INSUFICIENTE   MEDIO-BAJO        MEDIO         ALTO 
         332          664         1340          429 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Generación de base de datos procesada con NA corregidos</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>simce2m2017_total<span class="sc">$</span>cod_depe2 <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(simce2m2017_total<span class="sc">$</span>cod_depe2)</span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a>simce2m2017_total<span class="sc">$</span>cod_grupo <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(simce2m2017_total<span class="sc">$</span>cod_grupo)</span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>simce2m2017_total<span class="sc">$</span>cdm_2017 <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(simce2m2017_total<span class="sc">$</span>cdm_2017)</span>
<span id="cb97-6"><a href="#cb97-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-7"><a href="#cb97-7" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(simce2m2017_total)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Categoría desempeño (cdm_2017) &lt;categorical&gt; 
# total N=2876 valid N=2765 mean=2.67 sd=0.88

Value        |    N | Raw % | Valid % | Cum. %
----------------------------------------------
INSUFICIENTE |  332 | 11.54 |   12.01 |  12.01
MEDIO-BAJO   |  664 | 23.09 |   24.01 |  36.02
MEDIO        | 1340 | 46.59 |   48.46 |  84.48
ALTO         |  429 | 14.92 |   15.52 | 100.00
&lt;NA&gt;         |  111 |  3.86 |    &lt;NA&gt; |   &lt;NA&gt;

Código dependencia (cod_depe2) &lt;categorical&gt; 
# total N=2876 valid N=2876 mean=1.86 sd=0.63

Value                    |    N | Raw % | Valid % | Cum. %
----------------------------------------------------------
Municipal                |  805 | 27.99 |   27.99 |  27.99
Particular subvencionado | 1676 | 58.28 |   58.28 |  86.27
Particular pagado        |  395 | 13.73 |   13.73 | 100.00
&lt;NA&gt;                     |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;

GSE (cod_grupo) &lt;categorical&gt; 
# total N=2876 valid N=2876 mean=2.68 sd=1.31

Value      |   N | Raw % | Valid % | Cum. %
-------------------------------------------
Bajo       | 628 | 21.84 |   21.84 |  21.84
Medio bajo | 816 | 28.37 |   28.37 |  50.21
Medio      | 674 | 23.44 |   23.44 |  73.64
Medio alto | 368 | 12.80 |   12.80 |  86.44
Alto       | 390 | 13.56 |   13.56 | 100.00
&lt;NA&gt;       |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(simce2m2017_total)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>, , cod_grupo = Bajo

              cod_depe2
cdm_2017       Municipal Particular subvencionado Particular pagado
  INSUFICIENTE        93                       35                 0
  MEDIO-BAJO         175                       76                 0
  MEDIO              107                       95                 0
  ALTO                 2                        6                 0

, , cod_grupo = Medio bajo

              cod_depe2
cdm_2017       Municipal Particular subvencionado Particular pagado
  INSUFICIENTE        82                       53                 0
  MEDIO-BAJO          95                      157                 0
  MEDIO               90                      258                 0
  ALTO                17                       42                 0

, , cod_grupo = Medio

              cod_depe2
cdm_2017       Municipal Particular subvencionado Particular pagado
  INSUFICIENTE        12                       24                 1
  MEDIO-BAJO          15                       94                 0
  MEDIO               34                      348                 0
  ALTO                26                      103                 0

, , cod_grupo = Medio alto

              cod_depe2
cdm_2017       Municipal Particular subvencionado Particular pagado
  INSUFICIENTE         0                        8                 1
  MEDIO-BAJO           1                       27                 3
  MEDIO                5                      207                15
  ALTO                 6                       83                 3

, , cod_grupo = Alto

              cod_depe2
cdm_2017       Municipal Particular subvencionado Particular pagado
  INSUFICIENTE         0                        0                23
  MEDIO-BAJO           0                        1                20
  MEDIO                0                       14               167
  ALTO                 0                        7               134</code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(simce2m2017_total,<span class="at">file =</span> <span class="st">"C:/Users/nachi/OneDrive/Documentos/Universidad/UAH 5° Semestre/OFC R para análisis estadístico/Trabajos/input/data-proc/simce2m2017_total.RData"</span>)</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Guardar y respaldar base simce2m2017_total &gt; simce2m2017_final</span></span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>simce2m2017_final <span class="ot">&lt;-</span> simce2m2017_total</span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(simce2m2017_final,<span class="at">file =</span> <span class="st">"C:/Users/nachi/OneDrive/Documentos/Universidad/UAH 5° Semestre/OFC R para análisis estadístico/Trabajos/input/data-proc/simce2m2017_final.RData"</span>)</span>
<span id="cb101-7"><a href="#cb101-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-8"><a href="#cb101-8" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"~/Universidad/UAH 5° Semestre/OFC R para análisis estadístico/Trabajos/input/data-proc/simce2m2017_final.RData"</span>)</span>
<span id="cb101-9"><a href="#cb101-9" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(simce2m2017_final)</span>
<span id="cb101-10"><a href="#cb101-10" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(simce2m2017_final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2876    3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Eliminar casos perdidos</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(simce2m2017_final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2876    3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(simce2m2017_final))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 111</code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(simce2m2017_final)</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a>simce2m2017_final <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(simce2m2017_final)</span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(simce2m2017_final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2765    3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Etiquetado Final</span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a>simce2m2017_final <span class="ot">&lt;-</span>sjlabelled<span class="sc">::</span><span class="fu">copy_labels</span>(simce2m2017_final,simce2m2017_total)</span>
<span id="cb109-4"><a href="#cb109-4" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(simce2m2017_final)</span>
<span id="cb109-5"><a href="#cb109-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-6"><a href="#cb109-6" aria-hidden="true" tabindex="-1"></a>simce2m2017_final <span class="ot">&lt;-</span> simce2m2017_final</span>
<span id="cb109-7"><a href="#cb109-7" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(simce2m2017_final,<span class="at">file =</span> <span class="st">"C:/Users/nachi/OneDrive/Documentos/Universidad/UAH 5° Semestre/OFC R para análisis estadístico/Trabajos/input/data-proc/simce2m2017_final.RData"</span>)</span>
<span id="cb109-8"><a href="#cb109-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-9"><a href="#cb109-9" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"~/Universidad/UAH 5° Semestre/OFC R para análisis estadístico/Trabajos/input/data-proc/simce2m2017_final.RData"</span>)</span>
<span id="cb109-10"><a href="#cb109-10" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(simce2m2017_final)</span>
<span id="cb109-11"><a href="#cb109-11" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(simce2m2017_final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2765    3</code></pre>
</div>
</div>
</section>
<section id="visualización-e-interpretación-de-resultados" class="level4">
<h4 class="anchored" data-anchor-id="visualización-e-interpretación-de-resultados">4. Visualización e Interpretación de Resultados</h4>
<div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>summarytools<span class="sc">::</span><span class="fu">dfSummary</span>(simce2m2017_total, <span class="at">plain.ascii =</span> <span class="cn">FALSE</span>)</span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(<span class="fu">dfSummary</span>(simce2m2017_total, <span class="at">headings=</span><span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Switching method to 'browser'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Output file written: C:\Users\nachi\AppData\Local\Temp\RtmpI5gPcz\file4d002657aac.html</code></pre>
</div>
<div id="tbl-summarytools" class="cell tbl-parent quarto-layout-panel anchored">
<div class="panel-caption table-caption">
<p><strong>?(caption)</strong></p>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<pre><code>### Data Frame Summary  
#### simce2m2017_total  
**Dimensions:** 2876 x 3  
**Duplicates:** 2824  

----------------------------------------------------------------------------------------------------------------------------------
No   Variable     Label                 Stats / Values                  Freqs (% of Valid)   Graph            Valid      Missing  
---- ------------ --------------------- ------------------------------- -------------------- ---------------- ---------- ---------
1    cdm_2017\    Categoría desempeño   1\. INSUFICIENTE\               332 (12.0%)\         II \             2765\      111\     
     [factor]                           2\. MEDIO-BAJO\                 664 (24.0%)\         IIII \           (96.1%)    (3.9%)   
                                        3\. MEDIO\                      1340 (48.5%)\        IIIIIIIII \                          
                                        4\. ALTO                        429 (15.5%)          III                                  

2    cod_depe2\   Código dependencia    1\. Municipal\                  805 (28.0%)\         IIIII \          2876\      0\       
     [factor]                           2\. Particular subvencionado\   1676 (58.3%)\        IIIIIIIIIII \    (100.0%)   (0.0%)   
                                        3\. Particular pagado           395 (13.7%)          II                                   

3    cod_grupo\   GSE                   1\. Bajo\                       628 (21.8%)\         IIII \           2876\      0\       
     [factor]                           2\. Medio bajo\                 816 (28.4%)\         IIIII \          (100.0%)   (0.0%)   
                                        3\. Medio\                      674 (23.4%)\         IIII \                               
                                        4\. Medio alto\                 368 (12.8%)\         II \                                 
                                        5\. Alto                        390 (13.6%)          II                                   
----------------------------------------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
</div>
</div>
<p>Como podemos ver en la <strong>?@tbl-summarytools</strong> en la Categoría de Desempeño Académico (cdm_2017), la mayoría de los establecimientos tienen un desempeño académico medio (48.5%), seguido por un desempeño medio-bajo (24.0%), mientras que una menor concentración de establecimientos se encuentra en los extremos de los percentiles de desempeño ( un 15.5% y 12.0%). En cuanto al Código de Dependencia del Establecimiento (cod_depe2), una gran mayoría (1676 de 2876) son establecimientos subvencionados y solo un 13.7% son particulares pagados, mientras que los municipales llegan al 28%, considerando que para la categoría de GSE (cod_grupo), más del 50% de los establecimientos se encuentran entre el Medio y el Bajo, podríamos decir que el 13.6% de los colegios está dirigido a una elite.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>graph1 <span class="ot">&lt;-</span> simce2m2017_final <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> cdm_2017)) <span class="sc">+</span> </span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"coral"</span>)<span class="sc">+</span></span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Categoría de Desempeño 2017"</span>,</span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Categoría de Desempeño"</span>,</span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>) <span class="sc">+</span></span>
<span id="cb115-6"><a href="#cb115-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb115-7"><a href="#cb115-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-8"><a href="#cb115-8" aria-hidden="true" tabindex="-1"></a>graph1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-cdm_2017" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Trabajo02_files/figure-html/fig-cdm_2017-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;1: “Categorías de Desempeño”</figcaption>
</figure>
</div>
</div>
</div>
<p>En el <a href="#fig-cdm_2017">Figure&nbsp;1</a> podemos ver una distribuición desigual entre las categorías anteriormente presentadas, donde sobresale el desempeño medio en la mayoria de los establecimientos para el grado de 2° medio en Chile, mientras que el segundo desempeño con mayor frecuencia es el MEDIO-BAJO, lo cual no es buen indicador ya que es el segundo peor de las cuatro categorías.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>graph2 <span class="ot">&lt;-</span> simce2m2017_final <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> cod_depe2)) <span class="sc">+</span> </span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"green"</span>)<span class="sc">+</span></span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Código de Dependencia Establecimiento"</span>,</span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Codigo Dependencia"</span>,</span>
<span id="cb116-5"><a href="#cb116-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>) <span class="sc">+</span></span>
<span id="cb116-6"><a href="#cb116-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb116-7"><a href="#cb116-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb116-8"><a href="#cb116-8" aria-hidden="true" tabindex="-1"></a>graph2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-cod_depe2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Trabajo02_files/figure-html/fig-cod_depe2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;2: “Código de Dependencia Establecimiento”</figcaption>
</figure>
</div>
</div>
</div>
<p>En el <a href="#fig-cod_depe2">Figure&nbsp;2</a> podemos ver como los colegios particulares pagados destacan por ser una minoría mientras que la cantidad de los establecimientos subvencionados es mucho mayor a cualquiera de las otras dos, nuevamente esto dice mucho de la poca importancia que se le da a crear más educación pública municipal.</p>
<p>En conclusión todavía no se pueden hacer aseveraciones sobre la hipótesis inicial sin embargo para más adelante podremos ver como los resultados están relacionados tanto con el GSE como con el tipo de establecimiento.</p>
</section>
</section>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Favor revisar corrección del Trabajo01<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Bases de Datos (agenciaeducacion.cl)<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><a href="https://bcn.cl/2lh80" class="uri">https://bcn.cl/2lh80</a><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>